steps:
# Etapa 1: Construir a imagem do container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/manutencao:$COMMIT_SHA', '.']

# Etapa 2: Enviar a imagem para o Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/manutencao:$COMMIT_SHA']

# Etapa 3: Executar migrações do banco de dados
- name: 'gcr.io/$PROJECT_ID/manutencao:$COMMIT_SHA'
  entrypoint: 'flask'
  args: ['db', 'upgrade']
  secretEnv: ['SECRET_KEY', 'JWT_SECRET_KEY', 'DATABASE_URI']

# Etapa 4: Fazer o deploy da nova versão com mais recursos
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
      'run',
      'deploy',
      'manutencao', 
      '--image', 'gcr.io/$PROJECT_ID/manutencao:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--min-instances=1',
      # --- NOVOS LIMITES DE RECURSOS ---
      '--memory=8Gi',
      '--cpu=4',
      # --- Configuração de Segredos ---
      '--set-secrets=SECRET_KEY=SECRET_KEY:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,DATABASE_URI=DATABASE_URI:latest'
    ]

# Define as imagens que serão criadas por este build
images:
- 'gcr.io/$PROJECT_ID/manutencao:$COMMIT_SHA'

# Configuração de Acesso ao Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/SECRET_KEY/versions/latest
    env: 'SECRET_KEY'
  - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET_KEY/versions/latest
    env: 'JWT_SECRET_KEY'
  - versionName: projects/$PROJECT_ID/secrets/DATABASE_URI/versions/latest
    env: 'DATABASE_URI'
