"""Criando as tabelas iniciais

Revision ID: 0342615a75d2
Revises: 
Create Date: 2025-10-23 10:31:44.444222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0342615a75d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('fabricante', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.String(length=4), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('motorista', sa.String(length=100), nullable=False),
    sa.Column('placa_1', sa.String(length=10), nullable=True),
    sa.Column('placa_2', sa.String(length=10), nullable=True),
    sa.Column('data_calibragem', sa.Date(), nullable=True),
    sa.Column('troca_oleo_diferencial', sa.Integer(), nullable=True),
    sa.Column('intervalo_oleo_diferencial', sa.Integer(), nullable=True),
    sa.Column('troca_oleo_cambio', sa.Integer(), nullable=True),
    sa.Column('intervalo_oleo_cambio', sa.Integer(), nullable=True),
    sa.Column('km_ultima_revisao_preventiva', sa.Integer(), nullable=True),
    sa.Column('km_ultima_revisao_intermediaria', sa.Integer(), nullable=True),
    sa.Column('km_troca_preventiva', sa.Integer(), nullable=False),
    sa.Column('km_troca_intermediaria', sa.Integer(), nullable=False),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('data_ultima_atualizacao_km', sa.DateTime(), nullable=True),
    sa.Column('data_ultima_revisao_preventiva', sa.Date(), nullable=True),
    sa.Column('data_ultima_revisao_intermediaria', sa.Date(), nullable=True),
    sa.Column('data_troca_oleo_diferencial', sa.Date(), nullable=True),
    sa.Column('data_troca_oleo_cambio', sa.Date(), nullable=True),
    sa.Column('data_proxima_calibragem', sa.Date(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('em_manutencao', sa.Boolean(), nullable=True),
    sa.Column('data_proxima_revisao_carreta', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('log_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('motorista', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('fabricante', sa.String(length=50), nullable=True),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('km_troca', sa.Integer(), nullable=True),
    sa.Column('data_troca', sa.Date(), nullable=True),
    sa.Column('data_proxima', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_bloqueio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_manutencao', sa.String(length=100), nullable=False),
    sa.Column('data_bloqueio', sa.DateTime(), nullable=False),
    sa.Column('km_bloqueio', sa.Integer(), nullable=False),
    sa.Column('liberado', sa.Boolean(), nullable=True),
    sa.Column('data_liberacao', sa.DateTime(), nullable=True),
    sa.Column('manutencao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manutencao_id'], ['manutencao.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_bloqueio')
    op.drop_table('manutencao')
    op.drop_table('log_sistema')
    op.drop_table('veiculo')
    op.drop_table('usuario')
    # ### end Alembic commands ###
