"""cria tabela log_sistema

Revision ID: 145300824b5f
Revises: c5c200ddafa7
Create Date: 2025-06-30 15:08:36.134750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145300824b5f'
down_revision = 'c5c200ddafa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_sistema')
    # ### end Alembic commands ###
