"""Atualiza estrutura do Veiculo

Revision ID: 1ee18269323a
Revises: 145300824b5f
Create Date: 2025-07-15 17:00:56.783544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee18269323a'
down_revision = '145300824b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('em_manutencao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_column('em_manutencao')

    # ### end Alembic commands ###
