"""Adiciona campos de intervalo para troca de óleo

Revision ID: 32a8bb070926
Revises: ccc3d2f11b2f
Create Date: 2025-06-30 10:31:12.772563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a8bb070926'
down_revision = 'ccc3d2f11b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervalo_oleo_diferencial', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intervalo_oleo_cambio', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_column('intervalo_oleo_cambio')
        batch_op.drop_column('intervalo_oleo_diferencial')

    # ### end Alembic commands ###
