"""Cria tabela HistoricoBloqueio

Revision ID: af991b8491e7
Revises: 
Create Date: 2025-09-08 09:51:55.648147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af991b8491e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_bloqueio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_manutencao', sa.String(length=100), nullable=False),
    sa.Column('data_bloqueio', sa.DateTime(), nullable=False),
    sa.Column('km_bloqueio', sa.Integer(), nullable=False),
    sa.Column('liberado', sa.Boolean(), nullable=True),
    sa.Column('data_liberacao', sa.DateTime(), nullable=True),
    sa.Column('manutencao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manutencao_id'], ['manutencao.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manutencao', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'GERAL'"))

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_column('data_proxima_calibragem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_proxima_calibragem', sa.DATE(), nullable=True))

    with op.batch_alter_table('manutencao', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'GERAL'"))

    op.drop_table('historico_bloqueio')
    # ### end Alembic commands ###
