"""estrutura nova com todos os campos

Revision ID: ccc3d2f11b2f
Revises: 
Create Date: 2025-06-30 09:37:05.890166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc3d2f11b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('fabricante', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.String(length=4), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=False),
    sa.Column('motorista', sa.String(length=100), nullable=False),
    sa.Column('placa_1', sa.String(length=10), nullable=True),
    sa.Column('placa_2', sa.String(length=10), nullable=True),
    sa.Column('data_calibragem', sa.Date(), nullable=True),
    sa.Column('troca_oleo_diferencial', sa.Integer(), nullable=True),
    sa.Column('troca_oleo_cambio', sa.Integer(), nullable=True),
    sa.Column('km_ultima_revisao_preventiva', sa.Integer(), nullable=True),
    sa.Column('km_ultima_revisao_intermediaria', sa.Integer(), nullable=True),
    sa.Column('km_troca_preventiva', sa.Integer(), nullable=False),
    sa.Column('km_troca_intermediaria', sa.Integer(), nullable=False),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('motorista', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('fabricante', sa.String(length=50), nullable=True),
    sa.Column('km_atual', sa.Integer(), nullable=True),
    sa.Column('km_troca', sa.Integer(), nullable=True),
    sa.Column('data_troca', sa.Date(), nullable=True),
    sa.Column('data_proxima', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manutencao')
    op.drop_table('veiculo')
    # ### end Alembic commands ###
