"""Adiciona campo data_proxima_revisao_carreta ao modelo Veiculo

Revision ID: cef647f9b4da
Revises: b3df8b00a42c
Create Date: 2025-08-07 14:29:06.728375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef647f9b4da'
down_revision = 'b3df8b00a42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_proxima_revisao_carreta', sa.Date(), nullable=True))
        batch_op.drop_column('data_proxima_calibragem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_proxima_calibragem', sa.DATE(), nullable=True))
        batch_op.drop_column('data_proxima_revisao_carreta')

    # ### end Alembic commands ###
