"""Adiciona campo tipo à tabela manutencao

Revision ID: e72ba0f9f3b5
Revises: b3eaa96bd547
Create Date: 2025-08-07 15:07:25.894521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72ba0f9f3b5'
down_revision = 'b3eaa96bd547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=False))

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_column('data_proxima_calibragem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_proxima_calibragem', sa.DATE(), nullable=True))

    with op.batch_alter_table('manutencao', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
